test_5

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -24,8 +24,16 @@ jobs:
 
       - name: Prepare deployment folder
         run: |
-          rm -rf *  # clear current branch contents
-          cp -r dev_branch/src/* ./
+          cd live_branch
+          echo "Contents of dev_branch:"
+          ls -R
+          if [ -d "../dev_branch/src" ]; then
+            rm -rf ./*  # Clear old site files
+            cp -r ../dev_branch/src/* ./
+          else
+            echo "ERROR: ../dev_branch/src/ not found!"
+            exit 1
+          fi
 
       - name: Commit and push changes
         run: |
